/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTenantSlugRouteImport } from './routes/app/$tenantSlug'
import { Route as AuthenticatedSuperRouteImport } from './routes/_authenticated/super'
import { Route as AppTenantSlugIndexRouteImport } from './routes/app/$tenantSlug/index'
import { Route as AuthenticatedSuperIndexRouteImport } from './routes/_authenticated/super/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AppTenantSlugWithdrawRouteImport } from './routes/app/$tenantSlug/withdraw'
import { Route as AppTenantSlugWalletsRouteImport } from './routes/app/$tenantSlug/wallets'
import { Route as AppTenantSlugTasksRouteImport } from './routes/app/$tenantSlug/tasks'
import { Route as AppTenantSlugShopRouteImport } from './routes/app/$tenantSlug/shop'
import { Route as AppTenantSlugReferRouteImport } from './routes/app/$tenantSlug/refer'
import { Route as AppTenantSlugProfileRouteImport } from './routes/app/$tenantSlug/profile'
import { Route as AppTenantSlugPayoutsRouteImport } from './routes/app/$tenantSlug/payouts'
import { Route as AppTenantSlugMinersRouteImport } from './routes/app/$tenantSlug/miners'
import { Route as AppTenantSlugMineRouteImport } from './routes/app/$tenantSlug/mine'
import { Route as AppTenantSlugHistoryRouteImport } from './routes/app/$tenantSlug/history'
import { Route as AppTenantSlugDepositRouteImport } from './routes/app/$tenantSlug/deposit'
import { Route as AppTenantSlugConvertRouteImport } from './routes/app/$tenantSlug/convert'
import { Route as AppTenantSlugAdminRouteImport } from './routes/app/$tenantSlug/admin'
import { Route as ApiPublicClientErrorRouteImport } from './routes/api/public/client-error'
import { Route as AuthenticatedSuperTenantsRouteImport } from './routes/_authenticated/super/tenants'
import { Route as AuthenticatedSuperTasksRouteImport } from './routes/_authenticated/super/tasks'
import { Route as AuthenticatedSuperCheckBotsRouteImport } from './routes/_authenticated/super/check-bots'
import { Route as AuthenticatedSuperAnnouncementsRouteImport } from './routes/_authenticated/super/announcements'
import { Route as AuthenticatedAdminNewAiRouteImport } from './routes/_authenticated/admin/new-ai'
import { Route as AuthenticatedAdminTenantIdRouteImport } from './routes/_authenticated/admin/$tenantId'
import { Route as AuthenticatedAdminTenantIdIndexRouteImport } from './routes/_authenticated/admin/$tenantId/index'
import { Route as AuthenticatedAdminTenantIdWithdrawalsRouteImport } from './routes/_authenticated/admin/$tenantId/withdrawals'
import { Route as AuthenticatedAdminTenantIdTasksRouteImport } from './routes/_authenticated/admin/$tenantId/tasks'
import { Route as AuthenticatedAdminTenantIdReferralsRouteImport } from './routes/_authenticated/admin/$tenantId/referrals'
import { Route as AuthenticatedAdminTenantIdMinersRouteImport } from './routes/_authenticated/admin/$tenantId/miners'
import { Route as AuthenticatedAdminTenantIdMilestonesRouteImport } from './routes/_authenticated/admin/$tenantId/milestones'
import { Route as AuthenticatedAdminTenantIdEconomicsRouteImport } from './routes/_authenticated/admin/$tenantId/economics'
import { Route as AuthenticatedAdminTenantIdBrandingRouteImport } from './routes/_authenticated/admin/$tenantId/branding'
import { Route as AuthenticatedAdminTenantIdAdsRouteImport } from './routes/_authenticated/admin/$tenantId/ads'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTenantSlugRoute = AppTenantSlugRouteImport.update({
  id: '/app/$tenantSlug',
  path: '/app/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperRoute = AuthenticatedSuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AppTenantSlugIndexRoute = AppTenantSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTenantSlugRoute,
} as any)
const AuthenticatedSuperIndexRoute = AuthenticatedSuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSuperRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AppTenantSlugWithdrawRoute = AppTenantSlugWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppTenantSlugRoute,
} as any)
const AppTenantSlugWalletsRoute = AppTenantSlugWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AppTenantSlugRoute,
} as any)
const AppTenantSlugTasksRoute = AppTenantSlugTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppTenantSlugRoute,
} as any)
const AppTenantSlugShopRoute = AppTenantSlugShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppTenantSlugRoute,
} as any)
const AppTenantSlugReferRoute = AppTenantSlugReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => AppTenantSlugRoute,
} as any)
const AppTenantSlugProfileRoute = AppTenantSlugProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppTenantSlugRoute,
} as any)
const AppTenantSlugPayoutsRoute = AppTenantSlugPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AppTenantSlugRoute,
} as any)
const AppTenantSlugMinersRoute = AppTenantSlugMinersRouteImport.update({
  id: '/miners',
  path: '/miners',
  getParentRoute: () => AppTenantSlugRoute,
} as any)
const AppTenantSlugMineRoute = AppTenantSlugMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => AppTenantSlugRoute,
} as any)
const AppTenantSlugHistoryRoute = AppTenantSlugHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppTenantSlugRoute,
} as any)
const AppTenantSlugDepositRoute = AppTenantSlugDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AppTenantSlugRoute,
} as any)
const AppTenantSlugConvertRoute = AppTenantSlugConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => AppTenantSlugRoute,
} as any)
const AppTenantSlugAdminRoute = AppTenantSlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppTenantSlugRoute,
} as any)
const ApiPublicClientErrorRoute = ApiPublicClientErrorRouteImport.update({
  id: '/api/public/client-error',
  path: '/api/public/client-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperTenantsRoute =
  AuthenticatedSuperTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedSuperRoute,
  } as any)
const AuthenticatedSuperTasksRoute = AuthenticatedSuperTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedSuperRoute,
} as any)
const AuthenticatedSuperCheckBotsRoute =
  AuthenticatedSuperCheckBotsRouteImport.update({
    id: '/check-bots',
    path: '/check-bots',
    getParentRoute: () => AuthenticatedSuperRoute,
  } as any)
const AuthenticatedSuperAnnouncementsRoute =
  AuthenticatedSuperAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedSuperRoute,
  } as any)
const AuthenticatedAdminNewAiRoute = AuthenticatedAdminNewAiRouteImport.update({
  id: '/admin/new-ai',
  path: '/admin/new-ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTenantIdRoute =
  AuthenticatedAdminTenantIdRouteImport.update({
    id: '/admin/$tenantId',
    path: '/admin/$tenantId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTenantIdIndexRoute =
  AuthenticatedAdminTenantIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminTenantIdRoute,
  } as any)
const AuthenticatedAdminTenantIdWithdrawalsRoute =
  AuthenticatedAdminTenantIdWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedAdminTenantIdRoute,
  } as any)
const AuthenticatedAdminTenantIdTasksRoute =
  AuthenticatedAdminTenantIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedAdminTenantIdRoute,
  } as any)
const AuthenticatedAdminTenantIdReferralsRoute =
  AuthenticatedAdminTenantIdReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedAdminTenantIdRoute,
  } as any)
const AuthenticatedAdminTenantIdMinersRoute =
  AuthenticatedAdminTenantIdMinersRouteImport.update({
    id: '/miners',
    path: '/miners',
    getParentRoute: () => AuthenticatedAdminTenantIdRoute,
  } as any)
const AuthenticatedAdminTenantIdMilestonesRoute =
  AuthenticatedAdminTenantIdMilestonesRouteImport.update({
    id: '/milestones',
    path: '/milestones',
    getParentRoute: () => AuthenticatedAdminTenantIdRoute,
  } as any)
const AuthenticatedAdminTenantIdEconomicsRoute =
  AuthenticatedAdminTenantIdEconomicsRouteImport.update({
    id: '/economics',
    path: '/economics',
    getParentRoute: () => AuthenticatedAdminTenantIdRoute,
  } as any)
const AuthenticatedAdminTenantIdBrandingRoute =
  AuthenticatedAdminTenantIdBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedAdminTenantIdRoute,
  } as any)
const AuthenticatedAdminTenantIdAdsRoute =
  AuthenticatedAdminTenantIdAdsRouteImport.update({
    id: '/ads',
    path: '/ads',
    getParentRoute: () => AuthenticatedAdminTenantIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/super': typeof AuthenticatedSuperRouteWithChildren
  '/app/$tenantSlug': typeof AppTenantSlugRouteWithChildren
  '/admin/$tenantId': typeof AuthenticatedAdminTenantIdRouteWithChildren
  '/admin/new-ai': typeof AuthenticatedAdminNewAiRoute
  '/super/announcements': typeof AuthenticatedSuperAnnouncementsRoute
  '/super/check-bots': typeof AuthenticatedSuperCheckBotsRoute
  '/super/tasks': typeof AuthenticatedSuperTasksRoute
  '/super/tenants': typeof AuthenticatedSuperTenantsRoute
  '/api/public/client-error': typeof ApiPublicClientErrorRoute
  '/app/$tenantSlug/admin': typeof AppTenantSlugAdminRoute
  '/app/$tenantSlug/convert': typeof AppTenantSlugConvertRoute
  '/app/$tenantSlug/deposit': typeof AppTenantSlugDepositRoute
  '/app/$tenantSlug/history': typeof AppTenantSlugHistoryRoute
  '/app/$tenantSlug/mine': typeof AppTenantSlugMineRoute
  '/app/$tenantSlug/miners': typeof AppTenantSlugMinersRoute
  '/app/$tenantSlug/payouts': typeof AppTenantSlugPayoutsRoute
  '/app/$tenantSlug/profile': typeof AppTenantSlugProfileRoute
  '/app/$tenantSlug/refer': typeof AppTenantSlugReferRoute
  '/app/$tenantSlug/shop': typeof AppTenantSlugShopRoute
  '/app/$tenantSlug/tasks': typeof AppTenantSlugTasksRoute
  '/app/$tenantSlug/wallets': typeof AppTenantSlugWalletsRoute
  '/app/$tenantSlug/withdraw': typeof AppTenantSlugWithdrawRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/super/': typeof AuthenticatedSuperIndexRoute
  '/app/$tenantSlug/': typeof AppTenantSlugIndexRoute
  '/admin/$tenantId/ads': typeof AuthenticatedAdminTenantIdAdsRoute
  '/admin/$tenantId/branding': typeof AuthenticatedAdminTenantIdBrandingRoute
  '/admin/$tenantId/economics': typeof AuthenticatedAdminTenantIdEconomicsRoute
  '/admin/$tenantId/milestones': typeof AuthenticatedAdminTenantIdMilestonesRoute
  '/admin/$tenantId/miners': typeof AuthenticatedAdminTenantIdMinersRoute
  '/admin/$tenantId/referrals': typeof AuthenticatedAdminTenantIdReferralsRoute
  '/admin/$tenantId/tasks': typeof AuthenticatedAdminTenantIdTasksRoute
  '/admin/$tenantId/withdrawals': typeof AuthenticatedAdminTenantIdWithdrawalsRoute
  '/admin/$tenantId/': typeof AuthenticatedAdminTenantIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/new-ai': typeof AuthenticatedAdminNewAiRoute
  '/super/announcements': typeof AuthenticatedSuperAnnouncementsRoute
  '/super/check-bots': typeof AuthenticatedSuperCheckBotsRoute
  '/super/tasks': typeof AuthenticatedSuperTasksRoute
  '/super/tenants': typeof AuthenticatedSuperTenantsRoute
  '/api/public/client-error': typeof ApiPublicClientErrorRoute
  '/app/$tenantSlug/admin': typeof AppTenantSlugAdminRoute
  '/app/$tenantSlug/convert': typeof AppTenantSlugConvertRoute
  '/app/$tenantSlug/deposit': typeof AppTenantSlugDepositRoute
  '/app/$tenantSlug/history': typeof AppTenantSlugHistoryRoute
  '/app/$tenantSlug/mine': typeof AppTenantSlugMineRoute
  '/app/$tenantSlug/miners': typeof AppTenantSlugMinersRoute
  '/app/$tenantSlug/payouts': typeof AppTenantSlugPayoutsRoute
  '/app/$tenantSlug/profile': typeof AppTenantSlugProfileRoute
  '/app/$tenantSlug/refer': typeof AppTenantSlugReferRoute
  '/app/$tenantSlug/shop': typeof AppTenantSlugShopRoute
  '/app/$tenantSlug/tasks': typeof AppTenantSlugTasksRoute
  '/app/$tenantSlug/wallets': typeof AppTenantSlugWalletsRoute
  '/app/$tenantSlug/withdraw': typeof AppTenantSlugWithdrawRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/super': typeof AuthenticatedSuperIndexRoute
  '/app/$tenantSlug': typeof AppTenantSlugIndexRoute
  '/admin/$tenantId/ads': typeof AuthenticatedAdminTenantIdAdsRoute
  '/admin/$tenantId/branding': typeof AuthenticatedAdminTenantIdBrandingRoute
  '/admin/$tenantId/economics': typeof AuthenticatedAdminTenantIdEconomicsRoute
  '/admin/$tenantId/milestones': typeof AuthenticatedAdminTenantIdMilestonesRoute
  '/admin/$tenantId/miners': typeof AuthenticatedAdminTenantIdMinersRoute
  '/admin/$tenantId/referrals': typeof AuthenticatedAdminTenantIdReferralsRoute
  '/admin/$tenantId/tasks': typeof AuthenticatedAdminTenantIdTasksRoute
  '/admin/$tenantId/withdrawals': typeof AuthenticatedAdminTenantIdWithdrawalsRoute
  '/admin/$tenantId': typeof AuthenticatedAdminTenantIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/super': typeof AuthenticatedSuperRouteWithChildren
  '/app/$tenantSlug': typeof AppTenantSlugRouteWithChildren
  '/_authenticated/admin/$tenantId': typeof AuthenticatedAdminTenantIdRouteWithChildren
  '/_authenticated/admin/new-ai': typeof AuthenticatedAdminNewAiRoute
  '/_authenticated/super/announcements': typeof AuthenticatedSuperAnnouncementsRoute
  '/_authenticated/super/check-bots': typeof AuthenticatedSuperCheckBotsRoute
  '/_authenticated/super/tasks': typeof AuthenticatedSuperTasksRoute
  '/_authenticated/super/tenants': typeof AuthenticatedSuperTenantsRoute
  '/api/public/client-error': typeof ApiPublicClientErrorRoute
  '/app/$tenantSlug/admin': typeof AppTenantSlugAdminRoute
  '/app/$tenantSlug/convert': typeof AppTenantSlugConvertRoute
  '/app/$tenantSlug/deposit': typeof AppTenantSlugDepositRoute
  '/app/$tenantSlug/history': typeof AppTenantSlugHistoryRoute
  '/app/$tenantSlug/mine': typeof AppTenantSlugMineRoute
  '/app/$tenantSlug/miners': typeof AppTenantSlugMinersRoute
  '/app/$tenantSlug/payouts': typeof AppTenantSlugPayoutsRoute
  '/app/$tenantSlug/profile': typeof AppTenantSlugProfileRoute
  '/app/$tenantSlug/refer': typeof AppTenantSlugReferRoute
  '/app/$tenantSlug/shop': typeof AppTenantSlugShopRoute
  '/app/$tenantSlug/tasks': typeof AppTenantSlugTasksRoute
  '/app/$tenantSlug/wallets': typeof AppTenantSlugWalletsRoute
  '/app/$tenantSlug/withdraw': typeof AppTenantSlugWithdrawRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/super/': typeof AuthenticatedSuperIndexRoute
  '/app/$tenantSlug/': typeof AppTenantSlugIndexRoute
  '/_authenticated/admin/$tenantId/ads': typeof AuthenticatedAdminTenantIdAdsRoute
  '/_authenticated/admin/$tenantId/branding': typeof AuthenticatedAdminTenantIdBrandingRoute
  '/_authenticated/admin/$tenantId/economics': typeof AuthenticatedAdminTenantIdEconomicsRoute
  '/_authenticated/admin/$tenantId/milestones': typeof AuthenticatedAdminTenantIdMilestonesRoute
  '/_authenticated/admin/$tenantId/miners': typeof AuthenticatedAdminTenantIdMinersRoute
  '/_authenticated/admin/$tenantId/referrals': typeof AuthenticatedAdminTenantIdReferralsRoute
  '/_authenticated/admin/$tenantId/tasks': typeof AuthenticatedAdminTenantIdTasksRoute
  '/_authenticated/admin/$tenantId/withdrawals': typeof AuthenticatedAdminTenantIdWithdrawalsRoute
  '/_authenticated/admin/$tenantId/': typeof AuthenticatedAdminTenantIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/super'
    | '/app/$tenantSlug'
    | '/admin/$tenantId'
    | '/admin/new-ai'
    | '/super/announcements'
    | '/super/check-bots'
    | '/super/tasks'
    | '/super/tenants'
    | '/api/public/client-error'
    | '/app/$tenantSlug/admin'
    | '/app/$tenantSlug/convert'
    | '/app/$tenantSlug/deposit'
    | '/app/$tenantSlug/history'
    | '/app/$tenantSlug/mine'
    | '/app/$tenantSlug/miners'
    | '/app/$tenantSlug/payouts'
    | '/app/$tenantSlug/profile'
    | '/app/$tenantSlug/refer'
    | '/app/$tenantSlug/shop'
    | '/app/$tenantSlug/tasks'
    | '/app/$tenantSlug/wallets'
    | '/app/$tenantSlug/withdraw'
    | '/admin/'
    | '/super/'
    | '/app/$tenantSlug/'
    | '/admin/$tenantId/ads'
    | '/admin/$tenantId/branding'
    | '/admin/$tenantId/economics'
    | '/admin/$tenantId/milestones'
    | '/admin/$tenantId/miners'
    | '/admin/$tenantId/referrals'
    | '/admin/$tenantId/tasks'
    | '/admin/$tenantId/withdrawals'
    | '/admin/$tenantId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/new-ai'
    | '/super/announcements'
    | '/super/check-bots'
    | '/super/tasks'
    | '/super/tenants'
    | '/api/public/client-error'
    | '/app/$tenantSlug/admin'
    | '/app/$tenantSlug/convert'
    | '/app/$tenantSlug/deposit'
    | '/app/$tenantSlug/history'
    | '/app/$tenantSlug/mine'
    | '/app/$tenantSlug/miners'
    | '/app/$tenantSlug/payouts'
    | '/app/$tenantSlug/profile'
    | '/app/$tenantSlug/refer'
    | '/app/$tenantSlug/shop'
    | '/app/$tenantSlug/tasks'
    | '/app/$tenantSlug/wallets'
    | '/app/$tenantSlug/withdraw'
    | '/admin'
    | '/super'
    | '/app/$tenantSlug'
    | '/admin/$tenantId/ads'
    | '/admin/$tenantId/branding'
    | '/admin/$tenantId/economics'
    | '/admin/$tenantId/milestones'
    | '/admin/$tenantId/miners'
    | '/admin/$tenantId/referrals'
    | '/admin/$tenantId/tasks'
    | '/admin/$tenantId/withdrawals'
    | '/admin/$tenantId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/super'
    | '/app/$tenantSlug'
    | '/_authenticated/admin/$tenantId'
    | '/_authenticated/admin/new-ai'
    | '/_authenticated/super/announcements'
    | '/_authenticated/super/check-bots'
    | '/_authenticated/super/tasks'
    | '/_authenticated/super/tenants'
    | '/api/public/client-error'
    | '/app/$tenantSlug/admin'
    | '/app/$tenantSlug/convert'
    | '/app/$tenantSlug/deposit'
    | '/app/$tenantSlug/history'
    | '/app/$tenantSlug/mine'
    | '/app/$tenantSlug/miners'
    | '/app/$tenantSlug/payouts'
    | '/app/$tenantSlug/profile'
    | '/app/$tenantSlug/refer'
    | '/app/$tenantSlug/shop'
    | '/app/$tenantSlug/tasks'
    | '/app/$tenantSlug/wallets'
    | '/app/$tenantSlug/withdraw'
    | '/_authenticated/admin/'
    | '/_authenticated/super/'
    | '/app/$tenantSlug/'
    | '/_authenticated/admin/$tenantId/ads'
    | '/_authenticated/admin/$tenantId/branding'
    | '/_authenticated/admin/$tenantId/economics'
    | '/_authenticated/admin/$tenantId/milestones'
    | '/_authenticated/admin/$tenantId/miners'
    | '/_authenticated/admin/$tenantId/referrals'
    | '/_authenticated/admin/$tenantId/tasks'
    | '/_authenticated/admin/$tenantId/withdrawals'
    | '/_authenticated/admin/$tenantId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AppTenantSlugRoute: typeof AppTenantSlugRouteWithChildren
  ApiPublicClientErrorRoute: typeof ApiPublicClientErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$tenantSlug': {
      id: '/app/$tenantSlug'
      path: '/app/$tenantSlug'
      fullPath: '/app/$tenantSlug'
      preLoaderRoute: typeof AppTenantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super': {
      id: '/_authenticated/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof AuthenticatedSuperRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/app/$tenantSlug/': {
      id: '/app/$tenantSlug/'
      path: '/'
      fullPath: '/app/$tenantSlug/'
      preLoaderRoute: typeof AppTenantSlugIndexRouteImport
      parentRoute: typeof AppTenantSlugRoute
    }
    '/_authenticated/super/': {
      id: '/_authenticated/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof AuthenticatedSuperIndexRouteImport
      parentRoute: typeof AuthenticatedSuperRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/app/$tenantSlug/withdraw': {
      id: '/app/$tenantSlug/withdraw'
      path: '/withdraw'
      fullPath: '/app/$tenantSlug/withdraw'
      preLoaderRoute: typeof AppTenantSlugWithdrawRouteImport
      parentRoute: typeof AppTenantSlugRoute
    }
    '/app/$tenantSlug/wallets': {
      id: '/app/$tenantSlug/wallets'
      path: '/wallets'
      fullPath: '/app/$tenantSlug/wallets'
      preLoaderRoute: typeof AppTenantSlugWalletsRouteImport
      parentRoute: typeof AppTenantSlugRoute
    }
    '/app/$tenantSlug/tasks': {
      id: '/app/$tenantSlug/tasks'
      path: '/tasks'
      fullPath: '/app/$tenantSlug/tasks'
      preLoaderRoute: typeof AppTenantSlugTasksRouteImport
      parentRoute: typeof AppTenantSlugRoute
    }
    '/app/$tenantSlug/shop': {
      id: '/app/$tenantSlug/shop'
      path: '/shop'
      fullPath: '/app/$tenantSlug/shop'
      preLoaderRoute: typeof AppTenantSlugShopRouteImport
      parentRoute: typeof AppTenantSlugRoute
    }
    '/app/$tenantSlug/refer': {
      id: '/app/$tenantSlug/refer'
      path: '/refer'
      fullPath: '/app/$tenantSlug/refer'
      preLoaderRoute: typeof AppTenantSlugReferRouteImport
      parentRoute: typeof AppTenantSlugRoute
    }
    '/app/$tenantSlug/profile': {
      id: '/app/$tenantSlug/profile'
      path: '/profile'
      fullPath: '/app/$tenantSlug/profile'
      preLoaderRoute: typeof AppTenantSlugProfileRouteImport
      parentRoute: typeof AppTenantSlugRoute
    }
    '/app/$tenantSlug/payouts': {
      id: '/app/$tenantSlug/payouts'
      path: '/payouts'
      fullPath: '/app/$tenantSlug/payouts'
      preLoaderRoute: typeof AppTenantSlugPayoutsRouteImport
      parentRoute: typeof AppTenantSlugRoute
    }
    '/app/$tenantSlug/miners': {
      id: '/app/$tenantSlug/miners'
      path: '/miners'
      fullPath: '/app/$tenantSlug/miners'
      preLoaderRoute: typeof AppTenantSlugMinersRouteImport
      parentRoute: typeof AppTenantSlugRoute
    }
    '/app/$tenantSlug/mine': {
      id: '/app/$tenantSlug/mine'
      path: '/mine'
      fullPath: '/app/$tenantSlug/mine'
      preLoaderRoute: typeof AppTenantSlugMineRouteImport
      parentRoute: typeof AppTenantSlugRoute
    }
    '/app/$tenantSlug/history': {
      id: '/app/$tenantSlug/history'
      path: '/history'
      fullPath: '/app/$tenantSlug/history'
      preLoaderRoute: typeof AppTenantSlugHistoryRouteImport
      parentRoute: typeof AppTenantSlugRoute
    }
    '/app/$tenantSlug/deposit': {
      id: '/app/$tenantSlug/deposit'
      path: '/deposit'
      fullPath: '/app/$tenantSlug/deposit'
      preLoaderRoute: typeof AppTenantSlugDepositRouteImport
      parentRoute: typeof AppTenantSlugRoute
    }
    '/app/$tenantSlug/convert': {
      id: '/app/$tenantSlug/convert'
      path: '/convert'
      fullPath: '/app/$tenantSlug/convert'
      preLoaderRoute: typeof AppTenantSlugConvertRouteImport
      parentRoute: typeof AppTenantSlugRoute
    }
    '/app/$tenantSlug/admin': {
      id: '/app/$tenantSlug/admin'
      path: '/admin'
      fullPath: '/app/$tenantSlug/admin'
      preLoaderRoute: typeof AppTenantSlugAdminRouteImport
      parentRoute: typeof AppTenantSlugRoute
    }
    '/api/public/client-error': {
      id: '/api/public/client-error'
      path: '/api/public/client-error'
      fullPath: '/api/public/client-error'
      preLoaderRoute: typeof ApiPublicClientErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super/tenants': {
      id: '/_authenticated/super/tenants'
      path: '/tenants'
      fullPath: '/super/tenants'
      preLoaderRoute: typeof AuthenticatedSuperTenantsRouteImport
      parentRoute: typeof AuthenticatedSuperRoute
    }
    '/_authenticated/super/tasks': {
      id: '/_authenticated/super/tasks'
      path: '/tasks'
      fullPath: '/super/tasks'
      preLoaderRoute: typeof AuthenticatedSuperTasksRouteImport
      parentRoute: typeof AuthenticatedSuperRoute
    }
    '/_authenticated/super/check-bots': {
      id: '/_authenticated/super/check-bots'
      path: '/check-bots'
      fullPath: '/super/check-bots'
      preLoaderRoute: typeof AuthenticatedSuperCheckBotsRouteImport
      parentRoute: typeof AuthenticatedSuperRoute
    }
    '/_authenticated/super/announcements': {
      id: '/_authenticated/super/announcements'
      path: '/announcements'
      fullPath: '/super/announcements'
      preLoaderRoute: typeof AuthenticatedSuperAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedSuperRoute
    }
    '/_authenticated/admin/new-ai': {
      id: '/_authenticated/admin/new-ai'
      path: '/admin/new-ai'
      fullPath: '/admin/new-ai'
      preLoaderRoute: typeof AuthenticatedAdminNewAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/$tenantId': {
      id: '/_authenticated/admin/$tenantId'
      path: '/admin/$tenantId'
      fullPath: '/admin/$tenantId'
      preLoaderRoute: typeof AuthenticatedAdminTenantIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/$tenantId/': {
      id: '/_authenticated/admin/$tenantId/'
      path: '/'
      fullPath: '/admin/$tenantId/'
      preLoaderRoute: typeof AuthenticatedAdminTenantIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminTenantIdRoute
    }
    '/_authenticated/admin/$tenantId/withdrawals': {
      id: '/_authenticated/admin/$tenantId/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/$tenantId/withdrawals'
      preLoaderRoute: typeof AuthenticatedAdminTenantIdWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedAdminTenantIdRoute
    }
    '/_authenticated/admin/$tenantId/tasks': {
      id: '/_authenticated/admin/$tenantId/tasks'
      path: '/tasks'
      fullPath: '/admin/$tenantId/tasks'
      preLoaderRoute: typeof AuthenticatedAdminTenantIdTasksRouteImport
      parentRoute: typeof AuthenticatedAdminTenantIdRoute
    }
    '/_authenticated/admin/$tenantId/referrals': {
      id: '/_authenticated/admin/$tenantId/referrals'
      path: '/referrals'
      fullPath: '/admin/$tenantId/referrals'
      preLoaderRoute: typeof AuthenticatedAdminTenantIdReferralsRouteImport
      parentRoute: typeof AuthenticatedAdminTenantIdRoute
    }
    '/_authenticated/admin/$tenantId/miners': {
      id: '/_authenticated/admin/$tenantId/miners'
      path: '/miners'
      fullPath: '/admin/$tenantId/miners'
      preLoaderRoute: typeof AuthenticatedAdminTenantIdMinersRouteImport
      parentRoute: typeof AuthenticatedAdminTenantIdRoute
    }
    '/_authenticated/admin/$tenantId/milestones': {
      id: '/_authenticated/admin/$tenantId/milestones'
      path: '/milestones'
      fullPath: '/admin/$tenantId/milestones'
      preLoaderRoute: typeof AuthenticatedAdminTenantIdMilestonesRouteImport
      parentRoute: typeof AuthenticatedAdminTenantIdRoute
    }
    '/_authenticated/admin/$tenantId/economics': {
      id: '/_authenticated/admin/$tenantId/economics'
      path: '/economics'
      fullPath: '/admin/$tenantId/economics'
      preLoaderRoute: typeof AuthenticatedAdminTenantIdEconomicsRouteImport
      parentRoute: typeof AuthenticatedAdminTenantIdRoute
    }
    '/_authenticated/admin/$tenantId/branding': {
      id: '/_authenticated/admin/$tenantId/branding'
      path: '/branding'
      fullPath: '/admin/$tenantId/branding'
      preLoaderRoute: typeof AuthenticatedAdminTenantIdBrandingRouteImport
      parentRoute: typeof AuthenticatedAdminTenantIdRoute
    }
    '/_authenticated/admin/$tenantId/ads': {
      id: '/_authenticated/admin/$tenantId/ads'
      path: '/ads'
      fullPath: '/admin/$tenantId/ads'
      preLoaderRoute: typeof AuthenticatedAdminTenantIdAdsRouteImport
      parentRoute: typeof AuthenticatedAdminTenantIdRoute
    }
  }
}

interface AuthenticatedSuperRouteChildren {
  AuthenticatedSuperAnnouncementsRoute: typeof AuthenticatedSuperAnnouncementsRoute
  AuthenticatedSuperCheckBotsRoute: typeof AuthenticatedSuperCheckBotsRoute
  AuthenticatedSuperTasksRoute: typeof AuthenticatedSuperTasksRoute
  AuthenticatedSuperTenantsRoute: typeof AuthenticatedSuperTenantsRoute
  AuthenticatedSuperIndexRoute: typeof AuthenticatedSuperIndexRoute
}

const AuthenticatedSuperRouteChildren: AuthenticatedSuperRouteChildren = {
  AuthenticatedSuperAnnouncementsRoute: AuthenticatedSuperAnnouncementsRoute,
  AuthenticatedSuperCheckBotsRoute: AuthenticatedSuperCheckBotsRoute,
  AuthenticatedSuperTasksRoute: AuthenticatedSuperTasksRoute,
  AuthenticatedSuperTenantsRoute: AuthenticatedSuperTenantsRoute,
  AuthenticatedSuperIndexRoute: AuthenticatedSuperIndexRoute,
}

const AuthenticatedSuperRouteWithChildren =
  AuthenticatedSuperRoute._addFileChildren(AuthenticatedSuperRouteChildren)

interface AuthenticatedAdminTenantIdRouteChildren {
  AuthenticatedAdminTenantIdAdsRoute: typeof AuthenticatedAdminTenantIdAdsRoute
  AuthenticatedAdminTenantIdBrandingRoute: typeof AuthenticatedAdminTenantIdBrandingRoute
  AuthenticatedAdminTenantIdEconomicsRoute: typeof AuthenticatedAdminTenantIdEconomicsRoute
  AuthenticatedAdminTenantIdMilestonesRoute: typeof AuthenticatedAdminTenantIdMilestonesRoute
  AuthenticatedAdminTenantIdMinersRoute: typeof AuthenticatedAdminTenantIdMinersRoute
  AuthenticatedAdminTenantIdReferralsRoute: typeof AuthenticatedAdminTenantIdReferralsRoute
  AuthenticatedAdminTenantIdTasksRoute: typeof AuthenticatedAdminTenantIdTasksRoute
  AuthenticatedAdminTenantIdWithdrawalsRoute: typeof AuthenticatedAdminTenantIdWithdrawalsRoute
  AuthenticatedAdminTenantIdIndexRoute: typeof AuthenticatedAdminTenantIdIndexRoute
}

const AuthenticatedAdminTenantIdRouteChildren: AuthenticatedAdminTenantIdRouteChildren =
  {
    AuthenticatedAdminTenantIdAdsRoute: AuthenticatedAdminTenantIdAdsRoute,
    AuthenticatedAdminTenantIdBrandingRoute:
      AuthenticatedAdminTenantIdBrandingRoute,
    AuthenticatedAdminTenantIdEconomicsRoute:
      AuthenticatedAdminTenantIdEconomicsRoute,
    AuthenticatedAdminTenantIdMilestonesRoute:
      AuthenticatedAdminTenantIdMilestonesRoute,
    AuthenticatedAdminTenantIdMinersRoute:
      AuthenticatedAdminTenantIdMinersRoute,
    AuthenticatedAdminTenantIdReferralsRoute:
      AuthenticatedAdminTenantIdReferralsRoute,
    AuthenticatedAdminTenantIdTasksRoute: AuthenticatedAdminTenantIdTasksRoute,
    AuthenticatedAdminTenantIdWithdrawalsRoute:
      AuthenticatedAdminTenantIdWithdrawalsRoute,
    AuthenticatedAdminTenantIdIndexRoute: AuthenticatedAdminTenantIdIndexRoute,
  }

const AuthenticatedAdminTenantIdRouteWithChildren =
  AuthenticatedAdminTenantIdRoute._addFileChildren(
    AuthenticatedAdminTenantIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedSuperRoute: typeof AuthenticatedSuperRouteWithChildren
  AuthenticatedAdminTenantIdRoute: typeof AuthenticatedAdminTenantIdRouteWithChildren
  AuthenticatedAdminNewAiRoute: typeof AuthenticatedAdminNewAiRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSuperRoute: AuthenticatedSuperRouteWithChildren,
  AuthenticatedAdminTenantIdRoute: AuthenticatedAdminTenantIdRouteWithChildren,
  AuthenticatedAdminNewAiRoute: AuthenticatedAdminNewAiRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AppTenantSlugRouteChildren {
  AppTenantSlugAdminRoute: typeof AppTenantSlugAdminRoute
  AppTenantSlugConvertRoute: typeof AppTenantSlugConvertRoute
  AppTenantSlugDepositRoute: typeof AppTenantSlugDepositRoute
  AppTenantSlugHistoryRoute: typeof AppTenantSlugHistoryRoute
  AppTenantSlugMineRoute: typeof AppTenantSlugMineRoute
  AppTenantSlugMinersRoute: typeof AppTenantSlugMinersRoute
  AppTenantSlugPayoutsRoute: typeof AppTenantSlugPayoutsRoute
  AppTenantSlugProfileRoute: typeof AppTenantSlugProfileRoute
  AppTenantSlugReferRoute: typeof AppTenantSlugReferRoute
  AppTenantSlugShopRoute: typeof AppTenantSlugShopRoute
  AppTenantSlugTasksRoute: typeof AppTenantSlugTasksRoute
  AppTenantSlugWalletsRoute: typeof AppTenantSlugWalletsRoute
  AppTenantSlugWithdrawRoute: typeof AppTenantSlugWithdrawRoute
  AppTenantSlugIndexRoute: typeof AppTenantSlugIndexRoute
}

const AppTenantSlugRouteChildren: AppTenantSlugRouteChildren = {
  AppTenantSlugAdminRoute: AppTenantSlugAdminRoute,
  AppTenantSlugConvertRoute: AppTenantSlugConvertRoute,
  AppTenantSlugDepositRoute: AppTenantSlugDepositRoute,
  AppTenantSlugHistoryRoute: AppTenantSlugHistoryRoute,
  AppTenantSlugMineRoute: AppTenantSlugMineRoute,
  AppTenantSlugMinersRoute: AppTenantSlugMinersRoute,
  AppTenantSlugPayoutsRoute: AppTenantSlugPayoutsRoute,
  AppTenantSlugProfileRoute: AppTenantSlugProfileRoute,
  AppTenantSlugReferRoute: AppTenantSlugReferRoute,
  AppTenantSlugShopRoute: AppTenantSlugShopRoute,
  AppTenantSlugTasksRoute: AppTenantSlugTasksRoute,
  AppTenantSlugWalletsRoute: AppTenantSlugWalletsRoute,
  AppTenantSlugWithdrawRoute: AppTenantSlugWithdrawRoute,
  AppTenantSlugIndexRoute: AppTenantSlugIndexRoute,
}

const AppTenantSlugRouteWithChildren = AppTenantSlugRoute._addFileChildren(
  AppTenantSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AppTenantSlugRoute: AppTenantSlugRouteWithChildren,
  ApiPublicClientErrorRoute: ApiPublicClientErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
